config/routes.rb
Rails.application.routes.draw do
  root 'landmarks#index'
  resources :landmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/landmark.rb
class Landmark < ApplicationRecord
  validates :name, presence: true, length: {maximum: 140, minimum: 3}
  validates :location, presence: true, length: {maximum: 100, minimum: 3}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index

  end
  
  def create

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController
  def index
    @landmarks = Landmark.first   
  end

  def new
    @landmark = Landmark.new
  end

  def create
    @landmark = Landmark.create(landmark_params)
    if @landmark.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @landmark = Landmark.find(params[:id])
  end

  def edit
    @landmark = Landmark.find(params[:id])
  end

  def update
    @landmark = Landmark.find(params[:id])

    @landmark.update_attributes(landmark_params)
    if @landmark.valid?
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @landmark = Landmark.find(params[:id])

    @landmark.destroy
    redirect_to root_path
  end

  private
  
  def landmark_params
    params.require(:landmark).permit(:name, :location)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landmarks_helper.rb
module LandmarksHelper
end

app/views/answers/index.html.erb
<h1>Jamaica Land of Beauty</h1>

app/views/landmarks/index.html.erb
<h1>A few facts about Jamaica West Indies</h1>


<p>
Jamaica is an island nation of the Greater Antilles, 240 kilometers (150 
in length and as much as 85 kilometers (50 mi) in width situated in the 
Caribbean Sea. It is 635 kilometers (391 mi) east of the Central American
mainland, 150 kilometers (93 mi) south of Cuba, and 180 kilometers (112 mi) 
west of the island of Hispaniola, on which Haiti and the Dominican Republic 
are situated. Its indigenous Arawakan-speaking Taíno inhabitants named the 
island Xaymaca, meaning either the "Land of Springs," or the "Land of Wood 
and Water." Formerly a Spanish possession known as Santiago, then the 
British West Indies Crown colony of Jamaica. It is the third most populous
Anglophone country in the Americas, after the United States and Canada.</p>
~
~
~
~

app/views/landmarks/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1><%= @landmark.name %></h1>
  <i><%= @landmark.location %></i>
  <br/><br/>

<!-- Comments Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">x</span>
          </button>
            <h4 class="modal-title" id="myModalLabel">Enter a Landmark</h4>
          </div>
          <%= simple_form_for @landmark, url: landmark_path(@landmark) do |f| %>
            <div class="modal-body">
              <%= f.input :name %>
              <%= f.input :location %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit "Add a Landmark", class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jamaica Land of Beuty</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="row">
      <div class="col-3">

<!-- Code for JM Flag Logo and Text overlay -->
        <%= link_to root_path, class: 'jmflag' do %>
          <div class="jmflag">
            <img src="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQU9GvsTNYhlW7TxLbe9W67JgOBMLxNiOxGTmZWUrcWOIVoIH-dyg" height="75" width="125"/>
              <div class="text-on-flag">
                <p>Jamaica Nice</p>
              </div>
          </div>
        <% end %>
<!-- End of JM Flag Logo and Text Code -->
      </div>


      <div class="col col-sm-4 hidden-xs-down slogan">
        <h2>Jamaica Land of Beauty</h2>
      </div>
      <div class="col-10 offset-1 offset-sm-0 col-sm-5 links">
    </header>


  <!--  Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">x</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Enter a Landmark</h4>
        </div>
          <%= simple_form_for Landmark.new do |f| %>
            <div class="modal-body">
              <%= f.input :name, label: "What is the name of the Landmark you want to add?" %>
              <br />
              <%= f.input :location %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.submit 'Add a Landmark', class: 'btn btn-danger' %>
            </div>
          <% end %>
      </div>
    </div>
  </div>

  <hr />

  <br class="clear" />


  <div class="container">
    <% if flash[:error].present? %>
      <div class="col-10 offset-1 alert alert-danger">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>
    <%= yield %>
  </div>

  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-6 footer-blurb">
      <!-- Trigger modal -->
        <%= link_to ' Enter Tourist Attractions Here', '#', data: {toggle: 'modal', target: '#myModal'} %>
          &nbsp;&nbsp;
        </div>
<!--          <p class="text-muted">Place sticky footer content here.</p>  -->
        </div>
      </div>
    </div>
  </div>

  </body>
</html>